# Analyze results with histograms and plots made from scratch
October 27, 2020

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import subprocess as sp
import sys
import os
import glob
import pickle 

from matplotlib.colors import LogNorm, PowerNorm, Normalize

In [2]:
from ipywidgets import *

In [3]:
%matplotlib widget

In [4]:
sys.path.append('/global/u1/v/vpa/project/jpt_notebooks/Cosmology/Cosmo_GAN/repositories/lbann_cosmogan/3_analysis/')
from modules_image_analysis import *

In [5]:
### Transformation functions for image pixel values
def f_transform(x):
    return 2.*x/(x + 4.) - 1.

def f_invtransform(s):
    return 4.*(1. + s)/(1. - s)

## Read data

In [6]:
# main_dir='/global/cfs/cdirs/m3363/vayyar/cosmogan_data/results_from_other_code/pytorch/results/128sq/'
# results_dir=main_dir+'20201002_064327'

In [7]:
dict1={'128':'/global/cfs/cdirs/m3363/vayyar/cosmogan_data/results_from_other_code/pytorch/results/128sq/',
      '512':'/global/cfs/cdirs/m3363/vayyar/cosmogan_data/results_from_other_code/pytorch/results/512sq/'}

u=interactive(lambda x: dict1[x], x=Select(options=dict1.keys()))
# display(u)

In [8]:
# parent_dir=u.result
parent_dir=dict1['128']
dir_lst=[i.split('/')[-1] for i in glob.glob(parent_dir+'20*')]
w=interactive(lambda x: x, x=Dropdown(options=dir_lst))
display(w)

interactive(children=(Dropdown(description='x', options=('20201027_084012_with_spec_loss', '20201002_073628', â€¦

In [9]:
result=w.result
result_dir=parent_dir+result
print(result_dir)

### Read loss data
with open (result_dir+'/metrics.pickle','rb') as f:
    metrics_dict=pickle.load(f)

/global/cfs/cdirs/m3363/vayyar/cosmogan_data/results_from_other_code/pytorch/results/128sq/20201027_200951_with_spec_loss

In [10]:
metrics_dict

{'Dreal': array([137.40509033, 157.30966187, 178.44662476, ...,   0.80380142,
          0.53483164,          nan]),
 'Dfake': array([9.04761426e+03, 8.18200732e+03, 7.70663672e+03, ...,
        9.91677046e-02, 6.51771784e-01,            nan]),
 'Dfull': array([9.18501953e+03, 8.33931738e+03, 7.88508350e+03, ...,
        9.02969122e-01, 1.18660343e+00,            nan]),
 'G_adv': array([56.37857437, 56.25053024, 58.5247612 , ..., 79.35643005,
        71.77009583,         nan]),
 'G_full': array([56.37857437, 56.25053024, 58.5247612 , ..., 79.35643005,
        71.77009583,         nan]),
 'spec_loss': array([56.37857502, 56.25053191, 58.52476132, ..., 70.70386203,
        60.44644977,         nan]),
 'hist_loss': array([-3.77119803, -2.3533082 , -6.20673227, ..., -3.8683238 ,
        -3.89381289,         nan]),
 'spec_chi': array([        nan, 52.11718574, 49.36725362, ..., 54.31591418,
        63.33653468, 62.00715062]),
 'hist_chi': array([        nan,  3.7401309 ,  4.24530029, ..., -3.90590715,
        -3.88816857, -3.88999486])}

## Plot Losses

In [11]:
df_metrics=pd.DataFrame([])
for key in metrics_dict.keys(): df_metrics[key]=metrics_dict[key]
df_metrics['step']=np.arange(df_metrics.shape[0])
# df_metrics=df_metrics.dropna()

In [12]:
df_metrics.step.values.shape,df_metrics.G_full.values.shape

((62501,), (62501,))

In [13]:
df_metrics.head(10)

,Dreal,Dfake,Dfull,G_adv,G_full,spec_loss,hist_loss,spec_chi,hist_chi,step
0,137.405090,9047.614258,9185.019531,56.378574,56.378574,56.378575,-3.771198,NaN,NaN,0
1,157.309662,8182.007324,8339.317383,56.250530,56.250530,56.250532,-2.353308,52.117186,3.740131,1
2,178.446625,7706.636719,7885.083496,58.524761,58.524761,58.524761,-6.206732,49.367254,4.245300,2
3,146.841049,7514.710449,7661.551270,55.571075,55.571075,55.571077,-2.735018,53.457939,1.609068,3
4,152.817917,6617.784668,6770.602539,61.153759,61.153759,61.153759,-5.927526,50.071974,4.176231,4
5,149.953171,6563.671875,6713.625000,56.952232,56.952232,56.952234,-3.888446,53.159906,0.166687,5
6,158.958221,6322.425781,6481.383789,55.378399,55.378399,55.378398,-1.536845,59.648808,-2.987799,6
7,162.727890,5776.380859,5939.108887,58.972698,58.972698,58.972700,-6.501675,62.537671,-4.267967,7
8,147.698227,5820.820801,5968.519043,54.944939,54.944939,54.944939,-1.614692,52.542314,3.017538,8
9,159.571686,5424.105469,5583.677246,60.842770,60.842770,60.842770,-8.669691,55.924595,-1.884660,9

In [52]:
df_metrics[df_metrics.step%50==0].head(10)

,Dreal,Dfake,Dfull,G_adv,G_full,spec_loss,hist_loss,spec_chi,hist_chi,step
0,137.405090,9047.614258,9185.019531,56.378574,56.378574,56.378575,-3.771198,NaN,NaN,0
50,147.545441,3504.974609,3652.520020,59.711666,59.711666,59.711666,-7.862065,54.768552,0.175206,50
100,125.022812,4097.390625,4222.413574,148.126465,148.126465,148.126458,-3.873925,NaN,-3.863853,100
150,94.601868,2145.038086,2239.639893,129.111237,129.111237,129.111238,-3.896181,99.631662,-3.919198,150
200,202.211761,3127.039062,3329.250732,128.553696,128.553696,128.553692,-3.877437,NaN,-3.863853,200
250,70.161629,2601.832764,2671.994385,125.645744,125.645744,125.645742,-3.932847,147.512479,-3.897301,250
300,111.648926,3148.427734,3260.076660,135.675323,135.675323,109.698950,-3.894388,83.545665,-4.141774,300
350,57.004471,3656.783936,3713.788330,68.625679,68.625679,68.625683,0.400340,66.876371,0.160887,350
400,66.245461,3190.644531,3256.889893,107.158081,107.158081,84.359842,-5.853007,85.586305,-5.794026,400
450,42.929802,2670.016602,2712.946289,90.796890,90.796890,83.813598,-3.926219,76.147827,-4.800332,450

In [14]:
def f_plot_metrics(df,col_list):
    
    plt.figure()
    for key in col_list:
        plt.plot(df_metrics[key],label=key,marker='*',linestyle='')
    plt.legend()
    
#     col_list=list(col_list)
#     df.plot(kind='line',x='step',y=col_list)
    
# f_plot_metrics(df_metrics,['spec_chi','hist_chi'])

interact_manual(f_plot_metrics,df=fixed(df_metrics), col_list=SelectMultiple(options=df_metrics.columns.values))

interactive(children=(SelectMultiple(description='col_list', options=('Dreal', 'Dfake', 'Dfull', 'G_adv', 'G_fâ€¦

In [34]:
chi=df_metrics.quantile(q=0.005,axis=0)['hist_chi']
print(chi)
df_metrics[df_metrics['hist_chi']<=chi].sort_values(by=['hist_chi']).head(10)

-9.980233068466186

,Dreal,Dfake,Dfull,G_adv,G_full,spec_loss,hist_loss,spec_chi,hist_chi,step
11089,17.383606,0.990247,18.373854,75.109085,75.109085,51.912474,-3.931371,47.119395,-14.361295,11089
3706,1.851862,0.595583,2.447446,67.897133,67.897133,47.227941,-5.073976,48.904760,-14.299465,3706
8261,0.973155,0.697300,1.670455,98.713623,98.713623,47.544817,-4.125282,48.501333,-14.257017,8261
7865,2.205427,3.713712,5.919140,111.580292,111.580292,47.305408,-6.402421,47.066244,-13.820971,7865
13834,0.649989,0.724018,1.374007,84.054222,84.054222,48.511184,-4.997305,47.207708,-13.737056,13834
10075,1.468198,0.021533,1.489731,65.102852,65.102852,47.581029,-6.097039,48.443402,-13.275570,10075
10960,1.179214,1.606975,2.786190,87.437393,87.437393,47.823102,-6.059305,48.767608,-13.206313,10960
19262,0.152715,0.726454,0.879169,73.911102,73.911102,48.152155,-5.596090,49.579436,-13.155306,19262
15024,2.282143,0.154127,2.436270,58.874294,58.874294,49.661674,-4.209663,45.034483,-13.121076,15024
19259,0.064739,3.021429,3.086169,93.554100,93.554100,46.520116,-6.902633,49.303070,-13.021354,19259

In [36]:
display(df_metrics.sort_values(by=['hist_chi']).head(8))
display(df_metrics.sort_values(by=['spec_chi']).head(8))

,Dreal,Dfake,Dfull,G_adv,G_full,spec_loss,hist_loss,spec_chi,hist_chi,step
11089,17.383606,0.990247,18.373854,75.109085,75.109085,51.912474,-3.931371,47.119395,-14.361295,11089
3706,1.851862,0.595583,2.447446,67.897133,67.897133,47.227941,-5.073976,48.904760,-14.299465,3706
8261,0.973155,0.697300,1.670455,98.713623,98.713623,47.544817,-4.125282,48.501333,-14.257017,8261
7865,2.205427,3.713712,5.919140,111.580292,111.580292,47.305408,-6.402421,47.066244,-13.820971,7865
13834,0.649989,0.724018,1.374007,84.054222,84.054222,48.511184,-4.997305,47.207708,-13.737056,13834
10075,1.468198,0.021533,1.489731,65.102852,65.102852,47.581029,-6.097039,48.443402,-13.275570,10075
10960,1.179214,1.606975,2.786190,87.437393,87.437393,47.823102,-6.059305,48.767608,-13.206313,10960
19262,0.152715,0.726454,0.879169,73.911102,73.911102,48.152155,-5.596090,49.579436,-13.155306,19262

,Dreal,Dfake,Dfull,G_adv,G_full,spec_loss,hist_loss,spec_chi,hist_chi,step
6662,0.948255,0.953993,1.902248,77.573914,77.573914,46.734249,-5.274009,42.764675,-4.740591,6662
9620,0.985740,1.076406,2.062146,79.476685,79.476685,46.097935,-9.790718,42.963011,-4.119102,9620
52885,0.856697,0.254224,1.110921,60.856949,60.856949,47.175707,-4.305667,43.085706,-3.819711,52885
14191,0.325590,3.306780,3.632371,106.074875,106.074875,48.982248,-4.998256,43.166633,-8.302261,14191
6074,0.764230,1.649808,2.414038,93.938217,93.938217,48.577118,-4.444919,43.286033,-5.427243,6074
3472,1.432415,2.047306,3.479721,82.253563,82.253563,47.103766,-5.825348,43.351794,-4.037232,3472
16055,0.461207,1.109730,1.570937,76.399963,76.399963,47.708024,-5.552369,43.407460,-4.593754,16055
4317,0.588400,0.109091,0.697492,66.307732,66.307732,49.336726,-5.947022,43.452307,-2.804186,4317

## Read stored chi-squares for images

In [19]:
df=pd.read_pickle(result_dir+'/df_processed.pkle')
df[['epoch','step']]=df[['epoch','step']].astype(int)

chi1=df.quantile(q=0.2,axis=0)['chi_1']
chi_spec=df.quantile(q=0.2,axis=0)['chi_spec1']

df[(df.chi_spec1<chi_spec)&(df.chi_1<chi1)].sort_values(by=['chi_spec1','chi_1']).head(10)
# df[df.chi_1<chi1].sort_values(by=['chi_1']).head(5)

,epoch,step,img_type,fname,chi_1a,chi_1b,chi_1c,chi_1,chi_2,chi_imgvar,chi_spec1,chi_spec2,num_large,num_vlarge,hist_val,hist_err,hist_bin_centers,spec_val,spec_err
697,11,34800,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.011954,0.008893,0.064573,0.085419,0.010235,14.895751,0.293674,430.034506,0,0,"[1.1712546974829157, 0.8750739111074888, 0.266...","[0.016823394472101422, 0.014705840140681823, 0...","[-1.031746031584782, -0.6161616169043975, -0.3...","[76970.52280858159, 54471.48822243213, 38839.9...","[6306.421177965896, 2607.3966929839594, 1449.9..."
705,11,35200,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.009365,0.010581,0.004670,0.024616,0.003915,12.247101,0.353765,1615.134309,0,0,"[1.1312873690698122, 0.9086202993084255, 0.283...","[0.010905487760499852, 0.006638432859334996, 0...","[-1.031746031584782, -0.6161616169043975, -0.3...","[88752.88910913467, 66932.44186913669, 47176.9...","[6679.864919736757, 4451.214280741923, 2877.25..."
897,14,44800,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.003075,0.006034,0.040789,0.049898,0.000955,14.196412,0.361964,2038.085145,2,0,"[1.123009267365797, 0.937876762404334, 0.27567...","[0.013519581842051267, 0.010003912199922669, 0...","[-1.031746031584782, -0.6161616169043975, -0.3...","[98219.69898045063, 58743.87474197448, 43118.9...","[6142.833802638086, 3305.7865498805954, 2394.1..."
1102,17,55050,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.014967,0.004973,0.070242,0.090182,0.012868,10.331205,0.372904,2519.955381,3,0,"[1.1846603781739269, 0.8694267882388355, 0.252...","[0.005653374245419433, 0.0040903009765568665, ...","[-1.031746031584782, -0.6161616169043975, -0.3...","[67939.51198345423, 60109.89877515733, 42777.0...","[3390.998190894098, 1891.6014810794054, 1014.0..."
944,15,47150,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.012732,0.025854,0.044474,0.083060,0.008875,9.773603,0.376950,1977.287439,1,0,"[1.1603311330206882, 0.8801220967021944, 0.274...","[0.006117787460816783, 0.004933869598937693, 0...","[-1.031746031584782, -0.6161616169043975, -0.3...","[80976.27646300197, 67144.96099866407, 43769.5...","[8825.904009396245, 3979.9946048372576, 1554.2..."
536,8,26750,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.020817,0.008201,0.018245,0.047264,0.020284,11.292792,0.387159,1294.470305,3,0,"[1.195921900972902, 0.8410820079884926, 0.2580...","[0.008781172715521831, 0.007624961011649105, 0...","[-1.031746031584782, -0.6161616169043975, -0.3...","[75607.31331130862, 51620.815770626075, 41942....","[4584.541261609418, 2504.8817711413935, 1698.2..."
619,9,30900,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.017874,0.016942,0.058209,0.093025,0.017215,11.108729,0.391015,1602.234562,0,0,"[1.1917049319488113, 0.852296592117935, 0.2549...","[0.006785990958425488, 0.0077083509414187235, ...","[-1.031746031584782, -0.6161616169043975, -0.3...","[77093.99661421776, 57844.27841702402, 42349.8...","[6487.551648982558, 4546.00970395452, 2849.272..."
574,9,28650,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.046196,0.010323,0.051087,0.107607,0.044810,10.800103,0.397480,1045.876210,1,0,"[1.2400442393816933, 0.7882545602543004, 0.241...","[0.007985450536029374, 0.005944553220575649, 0...","[-1.031746031584782, -0.6161616169043975, -0.3...","[107170.25514565781, 61635.984729333024, 45154...","[6262.812622895707, 1966.7183729009253, 1407.9..."
1189,19,59400,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.010218,0.015473,0.052980,0.078671,0.008765,12.114837,0.398745,1163.292487,1,0,"[1.165013733530966, 0.8803492798061056, 0.2615...","[0.010214102338233262, 0.006896070440225015, 0...","[-1.031746031584782, -0.6161616169043975, -0.3...","[74492.04399100877, 53286.24274708034, 41026.8...","[3648.8734201677703, 1846.8322330136625, 1548...."
1054,16,52650,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.025084,0.004060,0.005017,0.034162,0.023188,12.011070,0.408533,938.809961,0,0,"[1.1963518590790987, 0.8298526717094457, 0.256...","[0.010360902571087715, 0.00803350949853674, 0....","[-1.031746031584782, -0.6161616169043975, -0.3...","[89490.5414070487, 75811.66312935352, 63379.80...","[5093.221168455256, 2704.12209582814, 2493.114..."

In [20]:
df[(df.chi_spec1<chi_spec)&(df.chi_1<chi1)].sort_values(by=['chi_1','chi_spec1']).head(5)
# df[df.chi_spec1<chi_spec].sort_values(by=['chi_spec1']).head(5)

,epoch,step,img_type,fname,chi_1a,chi_1b,chi_1c,chi_1,chi_2,chi_imgvar,chi_spec1,chi_spec2,num_large,num_vlarge,hist_val,hist_err,hist_bin_centers,spec_val,spec_err
705,11,35200,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.009365,0.010581,0.004670,0.024616,0.003915,12.247101,0.353765,1615.134309,0,0,"[1.1312873690698122, 0.9086202993084255, 0.283...","[0.010905487760499852, 0.006638432859334996, 0...","[-1.031746031584782, -0.6161616169043975, -0.3...","[88752.88910913467, 66932.44186913669, 47176.9...","[6679.864919736757, 4451.214280741923, 2877.25..."
757,12,37800,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.007692,0.018927,0.003765,0.030384,0.005358,9.106462,0.619300,3231.426497,1,0,"[1.1607028871911118, 0.9033950879184642, 0.260...","[0.0071359302462013705, 0.005769024962263378, ...","[-1.031746031584782, -0.6161616169043975, -0.3...","[84278.7488553673, 58749.17894428371, 44382.07...","[4177.873799930132, 2456.703590191136, 1779.99..."
1054,16,52650,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.025084,0.004060,0.005017,0.034162,0.023188,12.011070,0.408533,938.809961,0,0,"[1.1963518590790987, 0.8298526717094457, 0.256...","[0.010360902571087715, 0.00803350949853674, 0....","[-1.031746031584782, -0.6161616169043975, -0.3...","[89490.5414070487, 75811.66312935352, 63379.80...","[5093.221168455256, 2704.12209582814, 2493.114..."
669,10,33400,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.022234,0.012268,0.002514,0.037016,0.021388,10.745510,0.662107,2396.989776,1,0,"[1.1991062195235964, 0.838851482968272, 0.2562...","[0.010528702528715182, 0.009801756990285718, 0...","[-1.031746031584782, -0.6161616169043975, -0.3...","[66249.49656566652, 63045.910188123555, 51233....","[4357.7774023158345, 2736.8288439707067, 1920...."
891,14,44500,train,/global/cfs/cdirs/m3363/vayyar/cosmogan_data/r...,0.026849,0.006456,0.005977,0.039282,0.026088,12.242515,0.566584,2091.992909,0,0,"[1.2096561522690856, 0.8278906358120294, 0.244...","[0.011619319779006002, 0.00976809105163314, 0....","[-1.031746031584782, -0.6161616169043975, -0.3...","[80795.85102853179, 70149.913034302, 50958.484...","[4174.303169890969, 2945.752247562775, 1953.79..."

In [49]:
step_list=[34800,44800,35200,37800,11089,6662]
print([(j.epoch,j.step) for i,j in df[df.step.isin(step_list)][['epoch','step']].iterrows()])

[(2, 6662), (3, 11089), (11, 34800), (11, 35200), (12, 37800), (14, 44800)]

In [50]:
df_metrics[df_metrics.step.isin(step_list)]

,Dreal,Dfake,Dfull,G_adv,G_full,spec_loss,hist_loss,spec_chi,hist_chi,step
6662,0.948255,0.953993,1.902248,77.573914,77.573914,46.734249,-5.274009,42.764675,-4.740591,6662
11089,17.383606,0.990247,18.373854,75.109085,75.109085,51.912474,-3.931371,47.119395,-14.361295,11089
34800,1.117418,0.220851,1.338270,56.248024,56.248024,48.344951,-4.940057,48.410428,-4.526296,34800
35200,1.180596,0.464607,1.645203,55.452141,55.452141,48.227447,-4.624001,49.077579,-4.985753,35200
37800,0.110476,2.036795,2.147271,71.893570,71.893570,48.832157,-4.728548,49.808312,-4.033504,37800
44800,0.559803,0.372134,0.931937,56.842541,56.842541,48.252374,-4.741653,48.008844,-4.214592,44800

In [42]:
df[df.step.isin(step_list)][['epoch','step','chi_1','chi_spec1']]

     epoch   step     chi_1  chi_spec1
133      2   6662  0.565887  14.503054
222      3  11089  0.144374   3.302023
697     11  34800  0.085419   0.293674
705     11  35200  0.024616   0.353765
757     12  37800  0.030384   0.619300
897     14  44800  0.049898   0.361964

## Plot histogram and spectrum

In [24]:

def f_widget_compare(sample_names,sample_dict,bkgnd_arr,Fig_type='pixel',rescale=True,log_scale=True,bins=25,mode='avg',normalize=True,crop=False):
    '''
    Module to make widget plots for pixel intensity or spectrum comparison for multiple sample sets
    '''
    
    
    if crop: # Crop out large pixel values
        for key in sample_names:
            print(sample_dict[key].shape)
            sample_dict[key]=np.array([arr for arr in sample_dict[key] if np.max(arr)<=0.994])
            print(sample_dict[key].shape)
    
    img_list=[sample_dict[key] for key in sample_names]
    label_list=list(sample_names)
        
    hist_range=(0,0.996)
    
    if rescale: 
        for count,img in enumerate(img_list):
            img_list[count]=f_invtransform(img)
        hist_range=(0,2000)
        bkgnd_arr=f_invtransform(bkgnd_arr)
    
    assert Fig_type in ['pixel','spectrum'],"Invalid mode %s"%(mode)
    
    if Fig_type=='pixel':
        f_compare_pixel_intensity(img_lst=img_list,label_lst=label_list,bkgnd_arr=bkgnd_arr,normalize=normalize,log_scale=log_scale, mode=mode,bins=bins,hist_range=hist_range)
    elif Fig_type=='spectrum':
        f_compare_spectrum(img_lst=img_list,label_lst=label_list,bkgnd_arr=bkgnd_arr,log_scale=log_scale)

## Plot spectrum

In [25]:
dict_samples={}

In [26]:
# keras image for comparison
f1='/global/cfs/cdirs/m3363/vayyar/cosmogan_data/results_from_other_code/exagan1/run5_fixed_cosmology/models/gen_imgs.npy'
img_2=np.expand_dims(np.load(f1)[:500],axis=1)[:,0,:,:]
dict_samples['keras']=img_2

In [27]:
# Read input data

fname='/global/cfs/cdirs/m3363/vayyar/cosmogan_data/raw_data/128_square/dataset_2_smoothing_200k/norm_1_train_val.npy'
samples=np.load(fname,mmap_mode='r+')[:2000]
samples=samples[:,0,:,:]
print(samples.shape)
# dict_samples['val input']=samples

(2000, 128, 128)

In [37]:
for step in step_list:
    fname='*gen_img_epoch-*_step-{0}.npy'.format(step)
    fle=glob.glob(result_dir+'/images/'+fname)[0]
    imgs=np.load(fle)
#     img_list.append(imgs)
#     labels_list.append('Step:',step)
    strg='step:%s'%(step)
    dict_samples[strg]=imgs

In [39]:
bkgnd=samples

# bins=np.concatenate([np.array([-0.5]),np.arange(0.5,20.5,1),np.arange(20.5,100.5,5),np.arange(100.5,1000.5,50),np.array([2000])]) #bin edges to use
# bins=f_transform(bins)   ### scale to (-1,1) 
bins=50
interact_manual(f_widget_compare,sample_dict=fixed(dict_samples),
                sample_names=SelectMultiple(options=dict_samples.keys()), bkgnd_arr=fixed(bkgnd),
                Fig_type=ToggleButtons(options=['pixel','spectrum']),bins=fixed(bins),mode=['avg','simple'])

interactive(children=(SelectMultiple(description='sample_names', options=('keras', 'step:34800', 'step:44800',â€¦

## Plot images

In [63]:
f_plot_grid(bkgnd[100:118],cols=6,fig_size=(6,3))
f_plot_grid(dict_samples['step:39400'][40:58],cols=6,fig_size=(6,3))

3 6

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous â€¦

3 6

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous â€¦